fr = input('Digite uma frase:').lower().strip()
frase = fr.count('a')
letr1 = fr.index('a')
letr2 = fr.rindex('a')
print(f'A sua frase tem: {frase} letras "a"')
print(f'a primeira letra "a" aparece primeiro na str: {letr1}')
print(f'E a ultima letra aparece na str: {letr2}')
